# Generated by Django 5.2.1 on 2025-05-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_guardian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
