# Generated by Django 5.2.1 on 2025-05-17 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_delete_guardian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
