# Generated by Django 5.2.1 on 2025-05-14 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="budgeting.budget",
            ),
        ),
    ]
