# Generated by Django 5.2.1 on 2025-05-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_school", models.CharField(max_length=100)),
                ("grade_obtained", models.CharField(max_length=20)),
                ("pre_entry_test", models.BooleanField(default=False)),
                ("orientation_done", models.BooleanField(default=False)),
                ("registration_complete", models.BooleanField(default=False)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
